Lab submission
Greeph/python_fundamentals pull request #3
Opened 2021-05-28 08:12 UTC by Greeph

2021-05-29 06:57 UTC, giladgressel commented on 02_basic_datatypes/2_strings/02_09_vowel.py
> +print(dic)
nicely done. One way you can avoid the `if: else:` block for the dictionary checking would be to initialize the dictionary to have all the keys set to 0.
so `dic = {'a':0, 'e':0, 'i':0,'o':0,'u':0}`
then you can actually use `dic` in place of `vowels`, by doing `if letter in dic`.
This would simplify the code a bit.

2021-05-29 07:03 UTC, giladgressel commented on 02_basic_datatypes/2_strings/02_10_most_characters.py
> +    print(lenght3, user_string_3)
This challenge is good, but a little complicated.
I can think of two better ways to do it.

1) write a for-loop to find the maximum length and then print that
2) use the built-in `max()` python function to do that for you (without a for-loop)

2021-05-29 07:12 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_08_reorder.py
> +new_list=[user_numbers[1],user_numbers[3],user_numbers[5],user_numbers[7],user_numbers[9],user_numbers[8],user_numbers[6],user_numbers[4],user_numbers[2],user_numbers[0]]
So, this is hardcoding the solution.
I challenge you to make a solution that can take `n` input numbers, and sort them the same way. (assume `n` will always be even to make it simpler).

2021-05-29 07:14 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_09_flatten.py
> +print(finish_list)
Same comment as before  this is hardcoding the solution. It works in this case, but what if I gave you
`starting_list = [[1,2,3] , [1,2]]` would your solution work?

Further, think about these trickier cases

`[[1,2,3],1,2,3,[1,2,3,],[1,23]]`  how could you handle this?

2021-05-29 07:15 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_10_unique.py
> +        unique_list.append(element)
excellent! great job figuring out `not in`

2021-05-29 07:16 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_11_split.py
> +print(di)
great work 👍🏽

2021-05-29 07:17 UTC, giladgressel commented on 03_more_datatypes/3_tuples/03_14_list_of_tuples.py
> +print(word_tuples)
Nice work! This is a tricky one and you nailed it.

2021-05-29 07:19 UTC, giladgressel commented on 03_more_datatypes/3_tuples/03_16_pairing_tuples.py
> +#Come back later
Right so I wrote some comments in slack. but let's hash it out here
You got the sorted part
Now the next part, what makes it tricky? You need to basically "count by two's" on the list right? How do you select 2 elements of the list at a time? It's easy to do 1 at a time (that's the standard for loop). but what can you do to select 2 elements at a time?

two thoughts come to my mind
you can try something with the step size in slicing `mylist[::2]` will count by two's
you can try something with range `range(0,10,2)` will give you back `[0,2,4,6,8]`

Using those ideas, can you see how to make a loop that counts by twos?

2021-05-29 07:20 UTC, giladgressel commented on 03_more_datatypes/4_dictionaries/03_17_first_dict.py
> +print(result)
nice! This idea here, using `range()` could very useful for the counting by 2's problem you have earlier.

Also you can avoid the `i+1` if you do `range(1,n+1)`, that would just push the +1 into the range and make the code a bit cleaner.

2021-05-29 07:21 UTC, giladgressel commented on 03_more_datatypes/4_dictionaries/03_18_occurrence.py
> +print(result)
great

2021-05-29 07:23 UTC, giladgressel commented on 03_more_datatypes/4_dictionaries/03_20_dict_tuples.py
> +
hah, this is clearly googled - but I don't think there is another way to do it. Sorting is nasty, sorting dictionaries is even nastier. Good job

2021-05-29 07:24 UTC, giladgressel commented on 04_conditionals_loops/04_02_month.py
> +
excellent, and good formatting of the months so it's very readable (each one on it's own line)

2021-05-29 07:24 UTC, giladgressel commented on 04_conditionals_loops/04_04_prime.py
> +
nice!  Good use of break

2021-05-29 07:25 UTC, giladgressel commented on 04_conditionals_loops/04_07_search.py
> +            i=1
can you do this without the for-loop? (hint: yes)
I think you should find that, because while loops take awhile to get our heads around.

2021-05-29 07:26 UTC, giladgressel commented on 04_conditionals_loops/04_07_search.py
> +            i=1
hint: You will need to increment `i` within the while loop.

2021-05-29 07:28 UTC, giladgressel commented on 04_conditionals_loops/04_09_table.py
> +    print(x, x + 1, x + 2, x + 3, x + 4, x + 5, x + 6, x + 7, x + 8, x + 9)
This halfway hardcoded.  I think you can do better.
What if I wanted to have a loop that can do this, but I can easily change the length of each row, and how many rows (final value)  
You should be able to write code that does that, and all you need to do is change those few values.

2021-05-29 07:29 UTC, giladgressel commented on 05_string_formatting/05_01_fstring.py
> +    print(f'{quote} - {last_name}, {first_name} ')
nice work. Also impressed you caught the dijkstra problem.

Again though -- it's hardcoded for this specific person. What if there are other people with a middle initial? Can you make your code more general so it could catch that?

2021-05-29 07:34 UTC, giladgressel commented on 05_string_formatting/05_02_office_supplies.py
> +
This isn't quite working right?
This is the output I got with your code:
![image](https://user-images.githubusercontent.com/6275366/120062133-29861f00-c07e-11eb-8b0a-387960ab03ca.png)
The supplies are correctly right side, but the comma's are a bit off.

Check out these forum thread's on this subject if you are stuck.
https://forum.codingnomads.co/t/office-supplies-exercise/554
https://forum.codingnomads.co/t/05-02-office-supplies-formatting/875/6

2021-05-29 07:37 UTC, giladgressel requested changes
Overall excellent work. I left a lot of comments.  You only _need_ to make changes where I put the 👀 emoji. Those are places you can (and should) write more generalized code that will handle more use-cases.

2021-05-29 17:35 UTC, Greeph commented on 03_more_datatypes/2_lists/03_08_reorder.py
> +new_list=[user_numbers[1],user_numbers[3],user_numbers[5],user_numbers[7],user_numbers[9],user_numbers[8],user_numbers[6],user_numbers[4],user_numbers[2],user_numbers[0]]
Done

2021-05-29 17:35 UTC, Greeph commented on 03_more_datatypes/2_lists/03_09_flatten.py
> +print(finish_list)
Done

2021-05-29 18:04 UTC, Greeph commented on 03_more_datatypes/3_tuples/03_16_pairing_tuples.py
> +#Come back later
Also fix. This problem need it some time in the "freezer"

2021-05-29 18:19 UTC, Greeph commented on 04_conditionals_loops/04_07_search.py
> +            i=1
Done

2021-05-29 18:27 UTC, Greeph commented on 05_string_formatting/05_01_fstring.py
> +    print(f'{quote} - {last_name}, {first_name} ')
Done

2021-05-30 04:25 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_08_reorder.py
> +
nicely done!!

2021-05-30 04:28 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_09_flatten.py
> +    result=result+a
well done, this could be written a bit more pythonically.
```suggestion
    result  = []
    for sub_list in starting_list:
        results += sub_list
```
This gets you the same answer, but is a bit cleaner and easier to use.
As time goes you will get a better idea when you need to do a for-loop with range (and use the index) vs just do a for loop directly on the object.

2021-05-30 04:31 UTC, giladgressel commented on 03_more_datatypes/2_lists/03_09_flatten.py
> +    result=result+a
well done, this could be written a bit more pythonically.


```suggestion
result=[]
for sublist in starting_list:
    result += sublist
```

This gets you the same answer, but is a bit cleaner and easier to use.
As time goes you will get a better idea when you need to do a for-loop with range (and use the index) vs just do a for loop directly on the object.

2021-05-30 04:35 UTC, giladgressel commented on 03_more_datatypes/3_tuples/03_16_pairing_tuples.py
> +range_length=length//2
nice work using `len` and `//` to get an integer back.

2021-05-30 04:36 UTC, giladgressel commented on 03_more_datatypes/3_tuples/03_16_pairing_tuples.py
> +    range_length=range_length+1
excellent! You both added the zero if it's odd, and you remembered to update your length variable

However, had you done lines 18-19 _after_ this block, you would not have needed to update the length.
Sometimes the order of your operations can save you some lines of code.

in these small examples it does not matter. but at scale, doing less operations means things go faster.

2021-05-30 04:38 UTC, giladgressel commented on 03_more_datatypes/3_tuples/03_16_pairing_tuples.py
> +    result.append(a)
This is the super trick part and you've done it perfectly (and not even how I suggested)
Counting by 2's using 2* as your multiplier is excellent.

2021-05-30 04:39 UTC, giladgressel commented on 05_string_formatting/05_01_fstring.py
> +    print(f'{quote} - {last_name}, {first_name} ')
perfect

2021-06-03 12:13 UTC, Greeph commented on 05_string_formatting/05_02_office_supplies.py
> +
Done

2021-06-04 09:32 UTC, giladgressel commented
ok, everything looks good except except the one remaining lab, which I made an issue for - we can just do a new PR for that separately so this can be closed.

2021-06-04 09:32 UTC, merged